# Site Configuration
title: Craft of Electronics
number: TAD 265
tagline: Making Digital Electronics
markdown: kramdown
# This is the date that we render "upto."
upto: "20130111"

# Paths
## There are no heirarchies of variables; therefore, every
## path must be complete. A search-replace is necessary with
## any change to base.
base:
media: /downloads
arse:
    expanded: Active Reading Support Environment
    url: /downloads/active-reading-support-environment.docx
    version: 2

# Submission

moodle:
    root: http://moodle.berea.edu/
    a1: http://moodle.berea.edu/

# Shortcuts
table:
    start: '| :-: + :- + :-: |'
    end: '|====+====|'

pdf: '<img src="/images/mini-pdf.png" />'
word: '<img src="/images/mini-word.png" />'

group: '<i class="icon-group" style="margin-top: 6px;"> </i>'
lab: '<i class="icon-beaker" style="margin-top: 6px;"> </i>'
reading: '<i class="icon-book" style="margin-top: 6px;"> </i>'
prof: '<i class="icon-bullhorn" style="margin-top: 6px;"> </i>'
video: '<i class="icon-camera" style="margin-top: 6px;"> </i>'
download: '<i class="icon-download-alt" style="margin-top: 6px;"> </i>'
cloud: '<i class="icon-cloud" style="margin-top: 6px;"> </i>'
cart: '<i class="icon-shopping-cart" style="margin-top: 6px;"></i>'
talk: '<i class="icon-comments-alt" style="margin-top: 6px;"></i>'

  
# Server Config
permalink: /:categories/:title

# My Config
phone: 925-238-3692
officehours: M 9:30-11:30, T 13:30-15:30, by appt.
short: CRAFToE
prof-url: http://www.berea.edu/csc/matt-jadud/
