# Server config
auto: true
permalink: announce/:categories/:year/:month/:day/:title/

# Site configuration
title: Craft of Electronics
tagline: The Fall 2012 offering of Craft of Electronics @ Berea College
base: 
